project:
  type: book

book:
  title: "Quarto Template"
  favicon: images/exeter.png
  chapters:
    - index.qmd
    - pages/markdown.qmd
    - pages/frontmatter.qmd
    - pages/embed.qmd
    - pages/code.qmd
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/pythonhealthdatascience/quarto-template/
  sidebar:
    logo: images/exeter.png
