project:
  type: website

website:
  title: "Quarto Template"
  favicon: images/exeter.png
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/pythonhealthdatascience/quarto-template/
  sidebar:
    - logo: images/exeter.png
      contents:
        - text: Overview
          href: index.qmd
        - pages/markdown.qmd
        - pages/frontmatter.qmd
        - pages/embed.qmd
        - pages/code.qmd